---
sidebar: sidebar 
permalink: rn/about.html 
keywords: about, about this release, current release 
summary: A documentação neste local descreve a API REST do Astra Control e as tecnologias de automação relacionadas disponíveis com o Astra Control. 
---
= Sobre esta versão
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A documentação neste local descreve a API REST do Astra Control e as tecnologias de automação relacionadas incluídas nos dois modelos de implantação do Astra Control, conforme descrito abaixo.


NOTE: A cada versão do Astra Control é atribuído um número de versão do formulário *YY.MM*. Este valor identifica a versão com base no ano (_YY_) e no mês (_MM_) que ficou disponível. Por exemplo, o Astra Control Center 23,04 foi lançado em abril de 2023.

.Cadência de libertação
Em geral, as atualizações do Astra Control Service e do Astra Control Center ocorrem ao mesmo tempo. No entanto, o Astra Control Service tem uma cadência de lançamento acelerada que pode resultar em uma ou mais atualizações incrementais além da versão mais recente do Astra Control Center.

Como este site documenta a API REST para ambos os modelos de implantação, talvez haja alguns recursos disponíveis apenas com a versão mais recente do Astra Control Service. Quaisquer diferenças entre os dois modelos de implantação são observadas conforme necessário.

.Implantações do Astra Control
A documentação neste local se aplica aos seguintes lançamentos do Astra Control:

* Astra Control Center 23,04
* Astra Control Service 23,06


.Mais informações
Consulte as páginas e sites a seguir para obter mais informações sobre os lançamentos atuais e anteriores do Astra Control.

* link:../rn/whats_new.html["Novidades da API REST do Astra Control"]
* link:../endpoints/resources.html["Recursos REST e endpoints"]
* https://docs.netapp.com/us-en/astra-control-center-2304/["Documentação do Astra Control Center 23,04"^]
* link:../aa-earlier-versions.html["Versões anteriores da documentação do Astra Automation"]


.Ajude-nos a melhorar a documentação
Siga-nos no Twitter para receber notificações sobre a documentação do NetApp. Você também pode fornecer feedback tornando-se um link:https://docs.netapp.com/us-en/contribute/["Colaborador do GitHub"^] ou enviando um e-mail para NetApp.com_.
